project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - R Basics/**.qmd
    - Intro to Spatial Data/**.qmd

website:
  title: "LGEO2185: Advanced Geoprocessing"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - section: "R Basics"
        contents:
          - text: "Lecture"
            file: R Basics/LGEO2185_IntroductionR.qmd
          - text: "Assignment"
            file: R Basics/LGEO2185_IntroductionR_assignment.qmd
      - text: "Intro to Spatial Data"
        file: Intro to Spatial Data/LGEO2185_Intro_to_Spatial_Data.qmd


format:
  html:
    theme:
      - zephyr
      - _brand.yml
    css: styles.css
    toc: false
    standalone: true
    embed-resources: true

execute:
  echo: true
  warning: false
  error: false