project:
  type: website
  output-dir: docs
  render:
    - "!2025/"

website:
  title: "LGEO2185: Advanced Geoprocessing"

format:
  html:
    theme:
      - zephyr
      - _brand.yml
    css: styles.css
    toc: false
    standalone: true
    embed-resources: true

execute:
  echo: true
  warning: false
  error: false

