project:
  type: website
  output-dir: docs
  render:
    - R Basics/**.qmd

website:
  title: "LGEO2185: Advanced Geoprocessing"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Intro"
        href: "R Basics/LGEO2185_IntroductionR.qmd"
      - text: "Assignment"
        href: "R Basics/LGEO2185_IntroductionR_assignment.qmd"

format:
  html:
    theme:
      - zephyr
      - _brand.yml
    css: styles.css
    toc: false
    standalone: true
    embed-resources: true

execute:
  echo: true
  warning: false
  error: false